# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/lisa/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),lisa)

$(call add-radio-file-sha1-checked,radio/abl.img,e1850e29f759472ebc868e27c6d1169d4b3d4cff)
$(call add-radio-file-sha1-checked,radio/aop.img,68a996aee64d97770a4cf9575abfdb30d7ea91b5)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,2d0c8e0b3f20090524f914dd1953c533b5ad1b59)
$(call add-radio-file-sha1-checked,radio/cpucp.img,ef30feed60fbaaff864062ea04896b6e19fb880b)
$(call add-radio-file-sha1-checked,radio/devcfg.img,5c77441f90219e1832495e778beb8c06c7a41ec5)
$(call add-radio-file-sha1-checked,radio/dsp.img,c21e6e8bf124b76385a8f00c14baf084e9623352)
$(call add-radio-file-sha1-checked,radio/featenabler.img,1990bfee4fcaec0a69c81d9e5207b4ce49144c18)
$(call add-radio-file-sha1-checked,radio/hyp.img,cf5d857267c952b94ef7495ddd2142ac8cd686c4)
$(call add-radio-file-sha1-checked,radio/imagefv.img,a8016dbd39ca90d53f55020d7ad26fe233aa91bd)
$(call add-radio-file-sha1-checked,radio/keymaster.img,a77cf431d0920da71633c2eecd4e3e33e80d9a88)
$(call add-radio-file-sha1-checked,radio/modem.img,d811fd395ff7101b0980482db031ee2ac92ba002)
$(call add-radio-file-sha1-checked,radio/qupfw.img,35ce9d3f3b007d83bdd938839139fcfec0977895)
$(call add-radio-file-sha1-checked,radio/shrm.img,437f952a2997c146ce6639b0fe2867ac00b8c520)
$(call add-radio-file-sha1-checked,radio/tz.img,6a535a2ec17e872c0ed2b3b615a62f3d14bcc827)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,ae0bc909aa54801be28538805c3af56b0c97e993)
$(call add-radio-file-sha1-checked,radio/xbl.img,7cf4a6e06c0ca1061192ea7520547ee00bc765ca)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,9d1c52b3d9ff5dd682812acf24be30c428706393)

endif
