# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/lisa/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),lisa)

$(call add-radio-file-sha1-checked,radio/abl.img,0d6eb1e6d7fd76ecbe9d01f872b11763fed9596a)
$(call add-radio-file-sha1-checked,radio/aop.img,d38ea56cbc2d19c3502e1f95bb9158f7923f7801)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,d74a104fc49895f57673a4b57678d0a99f33d332)
$(call add-radio-file-sha1-checked,radio/cpucp.img,00c093de908b796639e4c4d2c7108b7fd302cc75)
$(call add-radio-file-sha1-checked,radio/devcfg.img,b37aec57323638a4b265c1bcfa8565f109f67346)
$(call add-radio-file-sha1-checked,radio/dsp.img,c21e6e8bf124b76385a8f00c14baf084e9623352)
$(call add-radio-file-sha1-checked,radio/featenabler.img,301e7be19d6dec0b041a3464fea83e6dd7cd5d1a)
$(call add-radio-file-sha1-checked,radio/hyp.img,1100ad162b8497bd14d69f9e1515c8cbe5bb1931)
$(call add-radio-file-sha1-checked,radio/imagefv.img,99dcdbe27fe5af49c97ebd90bcb48268be4b41c1)
$(call add-radio-file-sha1-checked,radio/keymaster.img,c976ed4370ab4acb7438ad138f09909c814fbc99)
$(call add-radio-file-sha1-checked,radio/modem.img,ca4f06e111d04ec8f630ea92f8180a26a00ccd06)
$(call add-radio-file-sha1-checked,radio/qupfw.img,3e601e669ed4623aeff34c339c652dcfaac70bda)
$(call add-radio-file-sha1-checked,radio/shrm.img,e1b58567c98421bb632d859a8fdd00a54835a283)
$(call add-radio-file-sha1-checked,radio/tz.img,e7df60ba378eabc5ca6c9b7828a3766ab7431178)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,421a65681bb1aa46064be4a2557b4a85e4b4253f)
$(call add-radio-file-sha1-checked,radio/xbl.img,8a5dba37748a97b9b036cc721c1666c2d05bb2c2)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,35e1331bf9875512bf2939f1d0f1a61311399e30)

endif
